# **Làm quen với Pytorch**

In [1]:
!pip install torch torchvision

In [3]:
!pip show torch

Name: torch
Version: 2.4.1+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.10/dist-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, easyocr, fastai, kornia, pytorch-ignite, pytorch-lightning, stable-baselines3, timm, torchaudio, torchmetrics, torchvision


In [10]:
import torch # pt dung giong numpy

In [11]:
x = torch.empty(5, 3) #cung cap 1 tensor ngau nhien nhung ko rong
x

tensor([[ 6.0745e-15,  3.2768e-41, -1.7768e+31],
        [ 4.3157e-41,  1.4013e-45,  0.0000e+00],
        [ 2.1019e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [12]:
x = torch.rand(5, 3) # cung cap 1 tensor random [0, 1]
x

tensor([[0.5963, 0.3679, 0.1965],
        [0.7527, 0.1827, 0.0880],
        [0.9716, 0.7220, 0.2698],
        [0.6697, 0.0110, 0.0072],
        [0.8602, 0.2342, 0.2266]])

In [13]:
x = torch.zeros(5, 3, dtype=torch.float) # tensor co 5 row, 3 col toan so 0
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
x = torch.ones(5, 3, dtype=torch.long) # tao ra tensor full 1
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [15]:
x = torch.Tensor(5, 3) # khai bao ra tensor
x

tensor([[ 6.0745e-15,  3.2768e-41, -1.7781e+31],
        [ 4.3157e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [16]:
a = [1, 4, 5, 3, 2]
x = torch.tensor(a, dtype=torch.int)
x

tensor([1, 4, 5, 3, 2], dtype=torch.int32)

In [17]:
y = torch.randn_like(x, dtype=torch.double) # tao ra 1 tensor kich thuoc giong x nhung lai random
y, y.shape

(tensor([-1.0998,  0.3614,  0.3500,  0.6665,  0.4308], dtype=torch.float64),
 torch.Size([5]))

In [18]:
# cong 2 phan tu
x = torch.ones(5, 3, dtype=torch.long)
y = torch.randn_like(x, dtype=torch.float)
z = x + y
z

tensor([[1.1645, 0.2623, 1.0171],
        [0.4160, 0.6507, 2.1491],
        [2.2411, 0.5539, 1.5106],
        [1.2806, 1.5191, 2.0418],
        [0.4385, 0.1966, 0.7935]])

In [19]:
# tru 2 phan tu
x = torch.ones(5, 3, dtype=torch.long)
y = torch.randn_like(x, dtype=torch.float)
z = x - y
z

tensor([[ 1.1571,  1.9678,  0.8416],
        [ 1.0727, -0.3183,  2.1097],
        [ 0.6027,  0.2523,  0.8925],
        [ 0.6910,  1.3822,  0.3076],
        [ 0.2165,  1.6706,  1.1555]])

In [20]:
x = torch.randint(0, 100, (5, 3))
x.shape, x


# x.view(15) == x.reshape(15) =)))
x = x.reshape((3,5)) 
x

tensor([[41, 63, 95, 17, 83],
        [91, 63, 51, 94, 69],
        [15, 98, 78, 79,  6]])

In [23]:
x[2, 1].item(), x[2][1] # 2 cai nay khac nhau nhe:)))

(98, tensor(98))

In [24]:
y = x.numpy()
y[2, 1]

98

In [30]:
import numpy as np
a = np.ones((4, 2), dtype=int)
b = torch.from_numpy(a) # chuyen tu numpy ve tensor
b

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

In [33]:
# kiem tra xem may co gpu khong?
device = torch.cuda.is_available()
device # false laf ko co, true la co

False

In [51]:
# nếu cuda khả dụng thì dùng, ko thì thôi:
x = torch.rand(5, 3) # khoi tao x la tensor
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) # khoi tao y tren cuda
    x = x.to(device) # chuyen x tu tensor ve cuda
else:
    print("Not ok:))")

Not ok:))


In [ ]:
# chuyen ve tinh toan tren cpu cpu()
x.cpu()